/* Farben und Stile des Generators. Neue Elemente nehmen ihre Werte von hier. */

/* ── 🎨 FARBPALETTE ── */
export const C = {
  cream:     "#FAF7F2",   // Hintergrund hell
  creamSoft: "#FEF8E0",   // Hintergrund ganz weich
  burgundy:  "#5C2818",   // Primär dunkel
  burgundyDark: "#3D1812",
  gold:      "#C9A84C",   // Akzent / Buttons
  goldSoft:  "#E0C77A",
  cappuccino:"#A88968",   // Mittelton
  ink:       "#1C1008",   // Haupttext dunkel
  inkSoft:   "#3D2817",
  border:    "#E8DCC4",
  white:     "#FFFFFF",
};

export const S = {
  /* Root & Layout */
  root: {
    minHeight: "100vh",
    background: `linear-gradient(180deg, ${C.creamSoft} 0%, ${C.cream} 60%)`,
    fontFamily: "'DM Sans', -apple-system, sans-serif",
    color: C.ink,
    display: "flex",
    flexDirection: "column",
  },

  /* Header */
  header: {
    background: C.burgundy,
    padding: "20px 24px",
    boxShadow: "0 2px 8px rgba(28,16,8,.08)",
    position: "sticky",
    top: 0,
    zIndex: 50,
  },
  headerInner: {
    maxWidth: 1100,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  logo: { display: "flex", flexDirection: "column", lineHeight: 1.1 },
  logoMain: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 26,
    fontWeight: 700,
    color: C.gold,
    fontStyle: "italic",
    letterSpacing: ".5px",
  },
  logoSub: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 11,
    color: C.cream,
    letterSpacing: "2px",
    textTransform: "uppercase",
    marginTop: 2,
    opacity: .8,
  },
  backBtn: {
    background: "transparent",
    border: `1.5px solid ${C.gold}`,
    color: C.gold,
    padding: "8px 16px",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    transition: "all .2s",
  },

  /* Stepper */
  stepperWrap: {
    background: C.cream,
    padding: "20px 16px",
    borderBottom: `1px solid ${C.border}`,
  },
  stepper: {
    maxWidth: 800,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
  },
  stepItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: 1,
    position: "relative",
  },
  stepCircle: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: C.cream,
    border: `2px solid ${C.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    color: C.cappuccino,
    transition: "all .3s",
    zIndex: 2,
    position: "relative",
  },
  stepCircleActive: {
    background: C.burgundy,
    borderColor: C.burgundy,
    color: C.gold,
    transform: "scale(1.15)",
    boxShadow: `0 0 0 4px ${C.gold}33`,
  },
  stepCircleDone: {
    background: C.gold,
    borderColor: C.gold,
    color: C.burgundy,
  },
  stepLabel: {
    fontSize: 11,
    marginTop: 6,
    letterSpacing: ".5px",
    textTransform: "uppercase",
    transition: "color .3s",
  },
  stepLine: {
    position: "absolute",
    top: 16,
    left: "60%",
    right: "-40%",
    height: 2,
    transition: "background .4s",
    zIndex: 1,
  },

  /* Main */
  main: {
    flex: 1,
    maxWidth: 1100,
    margin: "0 auto",
    width: "100%",
    padding: "40px 20px 60px",
  },

  /* Hero Block */
  heroBlock: {
    textAlign: "center",
    marginBottom: 40,
  },
  heroEyebrow: {
    fontSize: 11,
    fontWeight: 700,
    color: C.gold,
    letterSpacing: "3px",
    textTransform: "uppercase",
    marginBottom: 16,
  },
  heroTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 48,
    fontWeight: 600,
    color: C.burgundy,
    margin: "0 0 16px",
    lineHeight: 1.15,
    letterSpacing: "-.5px",
  },
  italic: {
    fontStyle: "italic",
    color: C.gold,
    fontWeight: 400,
  },
  heroSub: {
    fontSize: 18,
    color: C.inkSoft,
    margin: 0,
    lineHeight: 1.5,
    maxWidth: 560,
    marginInline: "auto",
  },

  /* Grids */
  grid: {
    display: "grid",
    gap: 16,
  },

  /* Step 1: Anlass-Karten */
  anlassCard: {
    background: C.white,
    border: `2px solid ${C.border}`,
    borderRadius: 20,
    overflow: "hidden",
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    padding: 0,
    boxShadow: "0 2px 8px rgba(28,16,8,.04)",
    display: "flex",
    flexDirection: "column",
  },
  anlassCardActive: {
    borderColor: C.gold,
    boxShadow: `0 8px 24px ${C.gold}40`,
    transform: "translateY(-4px)",
  },
  anlassImage: {
    height: 160,
    backgroundSize: "cover",
    backgroundPosition: "center",
    position: "relative",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    paddingBottom: 12,
  },
  anlassIconBig: {
    fontSize: 48,
    filter: "drop-shadow(0 2px 8px rgba(0,0,0,.4))",
  },
  anlassContent: { padding: "20px 22px 22px" },
  anlassLabel: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 700,
    color: C.burgundy,
    marginBottom: 4,
  },
  anlassSubtitle: {
    fontSize: 12,
    color: C.gold,
    fontWeight: 600,
    letterSpacing: "1px",
    textTransform: "uppercase",
    marginBottom: 8,
  },
  anlassDesc: {
    fontSize: 14,
    color: C.inkSoft,
    lineHeight: 1.5,
  },

  /* Step 2: Thema-Karten */
  themaCard: {
    background: C.white,
    border: `2px solid ${C.border}`,
    borderRadius: 20,
    padding: 0,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    position: "relative",
    boxShadow: "0 2px 8px rgba(28,16,8,.04)",
    minHeight: 360,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  themaCardActive: {
    borderColor: C.gold,
    boxShadow: `0 8px 24px ${C.gold}40`,
  },
  themaImage: {
    height: 160,
    backgroundSize: "cover",
    backgroundPosition: "center",
    flexShrink: 0,
  },
  themaContent: {
    padding: "20px 24px 24px",
    display: "flex",
    flexDirection: "column",
    flex: 1,
  },
  themaNumber: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 64,
    fontWeight: 700,
    color: C.gold,
    fontStyle: "italic",
    lineHeight: 1,
    opacity: .35,
    marginBottom: 12,
  },
  themaNumberSmall: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 14,
    fontWeight: 600,
    color: C.gold,
    fontStyle: "italic",
    letterSpacing: "1px",
    marginBottom: 6,
  },
  themaName: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 700,
    color: C.burgundy,
    marginBottom: 8,
    lineHeight: 1.2,
  },
  themaDesc: {
    fontSize: 14,
    color: C.inkSoft,
    lineHeight: 1.6,
    flex: 1,
  },
  themaArrow: {
    fontSize: 22,
    color: C.gold,
    marginTop: 16,
    fontWeight: 300,
  },

  /* Step 5: Menü-Anpassung */
  menueBilder: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 12,
    marginBottom: 24,
    maxWidth: 720,
    margin: "0 auto 24px",
  },
  menueBild: {
    aspectRatio: "1 / 1",
    borderRadius: 16,
    backgroundSize: "cover",
    backgroundPosition: "center",
    boxShadow: "0 4px 12px rgba(28,16,8,.10)",
    animation: "fadeUp .5s ease-out backwards",
  },
  menueCard: {
    background: C.white,
    borderRadius: 24,
    padding: 32,
    maxWidth: 720,
    margin: "0 auto",
    boxShadow: "0 8px 32px rgba(28,16,8,.06)",
    border: `1px solid ${C.border}`,
  },
  menueCardTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 22,
    fontWeight: 700,
    color: C.burgundy,
    marginBottom: 24,
    fontStyle: "italic",
  },
  menueKategorie: {
    marginBottom: 20,
  },
  menueKatLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: C.gold,
    letterSpacing: "1.5px",
    textTransform: "uppercase",
    marginBottom: 10,
  },
  menueFixItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: C.creamSoft,
    padding: "14px 16px",
    borderRadius: 12,
    fontSize: 15,
    color: C.ink,
    fontWeight: 500,
  },
  menueFixCheck: {
    color: C.gold,
    fontWeight: 700,
    fontSize: 16,
    flexShrink: 0,
  },
  menueWahlGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  menueWahlBtn: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: C.creamSoft,
    border: `2px solid ${C.border}`,
    borderRadius: 12,
    padding: "14px 16px",
    fontSize: 15,
    color: C.ink,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    transition: "all .2s",
  },
  menueWahlBtnActive: {
    background: C.white,
    borderColor: C.gold,
    boxShadow: `0 4px 12px ${C.gold}30`,
    fontWeight: 600,
  },
  menueRadio: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    border: `2px solid ${C.cappuccino}`,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all .2s",
  },
  menueRadioActive: {
    borderColor: C.gold,
  },
  menueRadioInner: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    background: C.gold,
  },
  menueZusatzHint: {
    fontSize: 12,
    color: C.cappuccino,
    marginTop: 8,
    fontStyle: "italic",
    lineHeight: 1.5,
  },

  /* Step 3: Form */
  formCard: {
    background: C.white,
    borderRadius: 24,
    padding: 36,
    maxWidth: 560,
    margin: "0 auto",
    boxShadow: "0 8px 32px rgba(28,16,8,.06)",
    border: `1px solid ${C.border}`,
  },
  field: { marginBottom: 24 },
  label: {
    display: "block",
    fontSize: 13,
    fontWeight: 700,
    color: C.burgundy,
    marginBottom: 10,
    letterSpacing: ".3px",
  },
  input: {
    width: "100%",
    padding: "14px 16px",
    fontSize: 15,
    border: `2px solid ${C.border}`,
    borderRadius: 12,
    background: C.creamSoft,
    color: C.ink,
    fontFamily: "inherit",
    boxSizing: "border-box",
    transition: "all .2s",
  },
  select: {
    width: "100%",
    padding: "14px 16px",
    fontSize: 15,
    border: `2px solid ${C.border}`,
    borderRadius: 12,
    background: C.creamSoft,
    color: C.ink,
    fontFamily: "inherit",
    cursor: "pointer",
    boxSizing: "border-box",
    appearance: "none",
    backgroundImage: `url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'><path fill='%235C2818' d='M6 8L0 0h12z'/></svg>")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 16px center",
    paddingRight: 40,
  },

  /* Toggle */
  toggleGroup: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  toggleBtn: {
    background: C.creamSoft,
    border: `2px solid ${C.border}`,
    borderRadius: 12,
    padding: "16px 18px",
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    transition: "all .2s",
  },
  toggleBtnActive: {
    background: C.white,
    borderColor: C.gold,
    boxShadow: `0 4px 12px ${C.gold}30`,
  },
  toggleLabel: {
    fontSize: 14,
    fontWeight: 700,
    color: C.burgundy,
    marginBottom: 4,
  },
  toggleDesc: {
    fontSize: 12,
    color: C.inkSoft,
  },

  /* Buttons */
  primaryBtn: {
    width: "100%",
    background: C.burgundy,
    color: C.gold,
    border: "none",
    padding: "18px 24px",
    fontSize: 16,
    fontWeight: 700,
    borderRadius: 14,
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
    letterSpacing: ".3px",
    transition: "all .25s",
    boxShadow: `0 4px 16px ${C.burgundy}40`,
  },
  btnDisabled: {
    opacity: .4,
    cursor: "not-allowed",
    boxShadow: "none",
  },

  /* Step 4: Pakete */
  paketCard: {
    background: C.white,
    border: `2px solid ${C.border}`,
    borderRadius: 24,
    padding: 32,
    cursor: "pointer",
    fontFamily: "inherit",
    textAlign: "left",
    position: "relative",
    boxShadow: "0 2px 8px rgba(28,16,8,.04)",
    display: "flex",
    flexDirection: "column",
  },
  paketCardFeatured: {
    background: C.burgundy,
    borderColor: C.gold,
    color: C.cream,
    transform: "scale(1.05)",
    boxShadow: `0 12px 32px ${C.burgundy}50`,
  },
  paketCardActive: {
    borderColor: C.gold,
    boxShadow: `0 12px 32px ${C.gold}50`,
  },
  paketBadge: {
    position: "absolute",
    top: -12,
    left: "50%",
    transform: "translateX(-50%)",
    fontSize: 11,
    fontWeight: 700,
    padding: "5px 14px",
    borderRadius: 20,
    letterSpacing: "1px",
    textTransform: "uppercase",
    boxShadow: "0 2px 8px rgba(0,0,0,.15)",
  },
  paketName: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 32,
    fontWeight: 700,
    marginBottom: 4,
  },
  paketTagline: {
    fontSize: 13,
    color: C.gold,
    fontWeight: 500,
    fontStyle: "italic",
    marginBottom: 24,
  },
  paketPriceWrap: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    marginBottom: 4,
  },
  paketPrice: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 42,
    fontWeight: 700,
    color: C.gold,
  },
  paketPriceUnit: {
    fontSize: 13,
    opacity: .7,
  },
  paketTotal: {
    fontSize: 13,
    opacity: .65,
    marginBottom: 20,
  },
  divider: {
    height: 1,
    background: "currentColor",
    opacity: .15,
    marginBottom: 20,
  },
  paketFeatures: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    flex: 1,
  },
  paketFeatureItem: {
    display: "flex",
    gap: 10,
    marginBottom: 10,
    fontSize: 14,
    lineHeight: 1.5,
  },
  checkmark: {
    color: C.gold,
    fontWeight: 700,
    flexShrink: 0,
  },
  paketCta: {
    marginTop: 24,
    padding: "14px 18px",
    borderRadius: 12,
    textAlign: "center",
    fontWeight: 700,
    fontSize: 14,
    letterSpacing: ".3px",
  },

  /* Step 5: Anfrage */
  summaryCard: {
    background: C.burgundy,
    color: C.cream,
    borderRadius: 24,
    padding: 32,
    boxShadow: "0 8px 32px rgba(28,16,8,.15)",
    height: "fit-content",
  },
  summaryTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 24,
    fontWeight: 700,
    color: C.gold,
    marginBottom: 24,
    fontStyle: "italic",
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: "10px 0",
    borderBottom: `1px solid ${C.cream}15`,
    gap: 16,
  },
  summaryLabel: {
    fontSize: 13,
    opacity: .7,
    flexShrink: 0,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: 600,
    textAlign: "right",
  },
  summaryDivider: {
    height: 2,
    background: C.gold,
    opacity: .3,
    margin: "20px 0 16px",
  },
  summarySubDivider: {
    height: 1,
    background: C.gold,
    opacity: .15,
    margin: "16px 0 8px",
  },
  summarySubTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: C.gold,
    letterSpacing: "1.5px",
    textTransform: "uppercase",
    marginBottom: 6,
    marginTop: 4,
  },
  summaryNotiz: {
    fontSize: 13,
    color: C.cream,
    fontStyle: "italic",
    lineHeight: 1.5,
    opacity: .9,
    padding: "4px 0 8px",
  },
  summaryBreakdown: {
    marginBottom: 16,
  },
  summaryBreakdownRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    padding: "6px 0",
    gap: 12,
  },
  summaryBreakdownLabel: {
    fontSize: 13,
    opacity: .8,
  },
  summaryBreakdownValue: {
    fontSize: 14,
    fontWeight: 600,
    color: C.cream,
  },
  summaryPriceRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 12,
  },
  summaryPriceLabel: {
    fontSize: 12,
    opacity: .8,
    textTransform: "uppercase",
    letterSpacing: "1px",
    marginBottom: 4,
  },
  summaryPriceSmall: { fontSize: 12, opacity: .6 },
  summaryPriceBig: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 36,
    fontWeight: 700,
    color: C.gold,
    lineHeight: 1,
  },
  summaryNote: {
    fontSize: 11,
    opacity: .6,
    fontStyle: "italic",
    marginTop: 12,
  },

  /* Kontakt-Buttons */
  kontaktGroup: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 8,
  },
  kontaktBtn: {
    background: C.creamSoft,
    border: `2px solid ${C.border}`,
    borderRadius: 12,
    padding: "16px 8px",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all .2s",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
  },
  kontaktBtnActive: {
    background: C.white,
    borderColor: C.gold,
    boxShadow: `0 4px 12px ${C.gold}40`,
  },
  kontaktIcon: { fontSize: 22 },
  kontaktLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: C.burgundy,
  },

  privacyNote: {
    fontSize: 11,
    color: C.cappuccino,
    marginTop: 16,
    textAlign: "center",
    lineHeight: 1.5,
  },

  /* Erfolgs-Screen */
  successWrap: {
    minHeight: "60vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  successCard: {
    background: C.white,
    borderRadius: 32,
    padding: "60px 40px",
    maxWidth: 540,
    textAlign: "center",
    boxShadow: "0 16px 48px rgba(28,16,8,.10)",
    border: `2px solid ${C.gold}40`,
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: "50%",
    background: C.gold,
    color: C.burgundy,
    fontSize: 40,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 24px",
    boxShadow: `0 8px 24px ${C.gold}60`,
  },
  successTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 42,
    fontWeight: 700,
    color: C.burgundy,
    margin: "0 0 16px",
  },
  successText: {
    fontSize: 16,
    color: C.inkSoft,
    lineHeight: 1.6,
    marginBottom: 28,
  },
  successIdBox: {
    background: C.creamSoft,
    border: `2px dashed ${C.gold}`,
    borderRadius: 16,
    padding: 20,
    marginBottom: 28,
  },
  successIdLabel: {
    fontSize: 11,
    color: C.gold,
    fontWeight: 700,
    letterSpacing: "2px",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  successIdNumber: {
    fontFamily: "'Playfair Display', serif",
    fontSize: 28,
    fontWeight: 700,
    color: C.burgundy,
    letterSpacing: "1px",
  },
  successFooter: {
    fontSize: 16,
    color: C.inkSoft,
    lineHeight: 1.6,
    marginBottom: 24,
  },
  successBackLink: {
    display: "inline-block",
    color: C.gold,
    fontSize: 14,
    fontWeight: 600,
    textDecoration: "none",
    borderBottom: `2px solid ${C.gold}`,
    paddingBottom: 2,
  },

  /* Footer */
  footer: {
    background: C.burgundy,
    color: C.cream,
    padding: "20px 16px",
    textAlign: "center",
  },
  footerText: {
    fontSize: 12,
    opacity: .7,
    fontFamily: "'DM Sans', sans-serif",
  },
  footerLink: {
    color: 'inherit',
    textDecoration: 'none',
    opacity: 1,
  },
};
